import Image from "next/image";
import HomeView from "@/src/pages/Home";
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: "Trang chủ Việt Xanh",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <HomeView />
  );
}
