import React from 'react'
import ProductView from '@/src/pages/Product'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: "Sản phẩm Việt Xanh",
  description: "Generated by create next app",
};

function ProductPage() {
  return (
    <ProductView />
  )
}

export default ProductPage